HaCreator - 64 for Bit client
lastbattle/Harepacker-resurrected pull request #171
Opened 2022-03-16 15:37 UTC by SoulGirlJP

I made an option to switch between 32 bit client and 64 bit client compatible, maybe its not optimal way and could just make the thing detect if it contains a Data folder, but anyways here is my take feel free to make it better, there is couple of issues like map simulator and some tile display issue not working, but i think the rest should be fine, it might need to get looked into it more since obviously not that perfect, like Map9_001.wz still needs to be loaded as i didn`t find a way to do this couple of things missing, but wanted to contribute to the community much love <3

2022-03-19 03:05 UTC, lastbattle commented
Hi,  I would appreciate if you are able to pull from the latest master branch, then opening up another pull request. 
It is overriding some of my prior changes.

Thanks a lot!

2022-03-20 23:53 UTC, SoulGirlJP commented
Ohhh yeh sure

2022-03-23 00:10 UTC, SoulGirlJP commented
Yeh i dunno why i am having such a hard time with Github

2022-03-23 06:55 UTC, lastbattle commented
It might be easier by just pulling the latest branch, and manually making the changes again 🤔

2022-03-24 22:32 UTC, SoulGirlJP commented
Hmm yeh ill just do it next week

2022-11-08 20:27 UTC, SoulGirlJP commented
After a long break i have decided to come back and pulled the latest changes as asked before, and i completely redid since i had a lot of issues with the last pull so i just pulled and redid all the code necessary to make it work again, as mentioned there is a lot of work to do still, i just wanted to help out the community and help the open source as best to my ability, if there is any questions please let me know! Much love <3

2022-11-09 15:18 UTC, lastbattle commented
I will take a look this weekend! Thanks a lot for your help, I appreciate it!!

2022-11-17 22:45 UTC, shailist requested changes
glossed around the changes and left some suggestions for cleaner code.
didn't really look into the internals and didn't verify if it even worked :shrug:, but looks good

2022-11-17 22:45 UTC, shailist commented on HaCreator/GUI/Initialization.cs
> +                    }
the only difference is which files we iterate, the loop is the same:
```cs
// Load sound
var soundWzFiles = isClient64() ? WzFileManager.SOUND_WZ_FILES_64 : WzFileManager.SOUND_WZ_FILES;
foreach (string soundWzFile in soundWzFiles )
{
    textBox2.Text = string.Format("Initializing {0}.wz...", soundWzFile);
    Application.DoEvents();
    Program.WzManager.LoadWzFile(soundWzFile.ToLower());
    Program.WzManager.ExtractSoundFile(soundWzFile.ToLower());
}
```

2022-11-17 22:45 UTC, shailist commented on HaCreator/GUI/Initialization.cs
> +                }
```cs
var mapWzFiles = isClient64() ? WzFileManager.MAP_WZ_FILES_64 : WzFileManager.MAP_WZ_FILES;
foreach (string mapwzFile in mapWzFiles )
{
    if (Program.WzManager.LoadWzFile(mapwzFile.ToLower()))
    {
        textBox2.Text = string.Format("Initializing {0}.wz...", mapwzFile);
        Application.DoEvents();
        Program.WzManager.ExtractBackgroundSets();
        Program.WzManager.ExtractObjSets();
    }
}
```

2022-11-17 22:45 UTC, shailist commented on HaCreator/MapEditor/Info/MobInfo.cs
> +                return null;
```cs
var mobWzFiles = Initialization.isClient64() ? WzFileManager.MOB_WZ_FILES_64 : WzFileManager.MOB_WZ_FILES;
foreach (string mobWzFile in mobWzFiles)
{
    WzImage mobImage = (WzImage)Program.WzManager[mobWzFile.ToLower()]?[id + ".img"];
    if (mobImage == null)
        continue;

    if (!mobImage.Parsed)
    {
        mobImage.ParseImage();
    }
    if (mobImage.HCTag == null)
    {
        mobImage.HCTag = MobInfo.Load(mobImage);
    }
    MobInfo result = (MobInfo)mobImage.HCTag;
    result.ParseImageIfNeeded();
    return result;
}
return null;
```

2022-11-19 17:09 UTC, Alon-Sachs commented
is there a way to add this to harepacker aswell?

2022-11-19 20:31 UTC, SoulGirlJP commented
Harepacker already works

On Sat., Nov. 19, 2022, 12:09 p.m. Alon-Sachs, ***@***.***>
wrote:

> is there a way to add this to harepacker aswell?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lastbattle/Harepacker-resurrected/pull/171#issuecomment-1320926500>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMJFFTYLT4FTURZUZK5KHNTWJECUJANCNFSM5Q4IKWBQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-11-24 08:51 UTC, Lingko621 commented
how can i use this program? and it works?
if it works  send me file please  ToT

2022-11-27 12:30 UTC, lastbattle commented
Looking at it now! Was away.

2022-11-28 00:14 UTC, merged

2022-11-28 00:15 UTC, lastbattle commented
Merged! I'll do a little clean up later, once again thanks for the contribution!

2022-11-28 00:48 UTC, SoulGirlJP commented
You are very welcome! I'm happy i was able to help!

On Sun., Nov. 27, 2022, 7:15 p.m. LastBattle, ***@***.***>
wrote:

> Merged! I'll do a little clean up later, once again thanks for the
> contribution!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lastbattle/Harepacker-resurrected/pull/171#issuecomment-1328379684>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMJFFTYK2YXDZR6OKLQ3V4DWKP2SHANCNFSM5Q4IKWBQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-11-30 02:36 UTC, lastbattle commented on HaCreator/MapEditor/Info/MobInfo.cs
> +                return null;
Pushed! thanks.
https://github.com/lastbattle/Harepacker-resurrected/commit/b37108aca618bfdf705b785f5090e6c5ecae7901

2022-12-02 08:02 UTC, lastbattle commented
I've made it better, feel free to take a look! 
It'll allow for better support for future versions of .wz files, as the location of the images, and directories are not static.

https://github.com/lastbattle/Harepacker-resurrected/commit/cee77e2c286ce77966cfe93118cc54004acc93f1

2022-12-02 21:57 UTC, SoulGirlJP commented
Amazing work, i wanted to do this too but i felt lazy haha good job!

Le ven. 2 déc. 2022 à 03:02, LastBattle ***@***.***> a écrit :

> I've made it better, feel free to take a look!
> It'll allow for better support for future versions of .wz files, as the
> location of the images, and directories are not static.
>
> cee77e2
> <https://github.com/lastbattle/Harepacker-resurrected/commit/cee77e2c286ce77966cfe93118cc54004acc93f1>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lastbattle/Harepacker-resurrected/pull/171#issuecomment-1334880080>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMJFFT2K4FAJTHQICYCFIPDWLGUKRANCNFSM5Q4IKWBQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-12-03 02:58 UTC, lastbattle commented
Exactly!! It was just so tedious.
That was the reason why I avoided doing it months after 64-client was released.
It kept being pushed back and at the same time I was busy on other personal stuff. I guess this pull request kind of forced me to 😀

2022-12-07 00:41 UTC, SoulGirlJP commented
Ahhh i see yeah well it's understandable hahahaha

Le ven. 2 déc. 2022 à 21:58, LastBattle ***@***.***> a écrit :

> Exactly!! It was just so tedious.
> That was the reason why I avoided doing it months after 64-client was
> released.
> It kept being pushed back and at the same time I was busy on other
> personal stuff. I guess this pull request kind of forced me to 😀
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/lastbattle/Harepacker-resurrected/pull/171#issuecomment-1336022632>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMJFFT2NKZSN4I3BV7DXJRTWLKZORANCNFSM5Q4IKWBQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>